# build-catalog.ps1 - Generates a FACTUAL catalog of Vibeforge skills and agents
# from the real frontmatter on disk. Anti-hallucination (frame 10): an orchestrator
# agent (lead) reads this catalog and CANNOT invent a skill/agent name that does not
# exist. Inspired by vibeflow-os's build-module-catalog.sh, ported to PowerShell and
# adapted to the Vibeforge structure.
#
# Usage: powershell.exe -ExecutionPolicy Bypass -File scripts/build-catalog.ps1
# Idempotent. Re-generates registres/CATALOG.md on each run. Zero hardcoded names.
#
# ASCII only (no em-dash): avoids CP1252 parsing issues on hooks/scripts.

param(
    [string]$Root = (Split-Path $PSScriptRoot -Parent),
    [string]$OutFile = ""
)

if ([string]::IsNullOrEmpty($OutFile)) {
    $OutFile = Join-Path $Root "registres\CATALOG.md"
}

function Get-Frontmatter {
    param([string]$Path)
    $lines = Get-Content -Path $Path -Encoding UTF8 -ErrorAction SilentlyContinue
    if (-not $lines -or $lines[0].Trim() -ne "---") { return $null }
    $fm = @{}
    for ($i = 1; $i -lt $lines.Count; $i++) {
        if ($lines[$i].Trim() -eq "---") { break }
        $line = $lines[$i]
        if ($line -match '^(name|description)\s*:\s*(.+)$') {
            $key = $matches[1]
            $val = $matches[2].Trim().Trim('"').Trim("'")
            if (-not $fm.ContainsKey($key)) { $fm[$key] = $val }
        }
    }
    return $fm
}

function Format-Desc {
    param([string]$Desc)
    if ([string]::IsNullOrEmpty($Desc)) { return "(no description)" }
    $d = $Desc -replace '\|', '/' -replace '\s+', ' '
    if ($d.Length -gt 160) { $d = $d.Substring(0, 157) + "..." }
    return $d
}

# --- Skills ---
$skillRows = @()
$skillsDir = Join-Path $Root "skills"
if (Test-Path $skillsDir) {
    Get-ChildItem $skillsDir -Directory | Sort-Object Name | ForEach-Object {
        $skillFile = Join-Path $_.FullName "SKILL.md"
        if (Test-Path $skillFile) {
            $fm = Get-Frontmatter $skillFile
            if ($fm) {
                $name = if ($fm.ContainsKey("name")) { $fm["name"] } else { $_.Name }
                $skillRows += "| ``/$name`` | $(Format-Desc $fm['description']) |"
            }
        }
    }
}

# --- Agents (excluding _archived) ---
$agentRows = @()
$agentsDir = Join-Path $Root "agents"
if (Test-Path $agentsDir) {
    Get-ChildItem $agentsDir -Filter "*.md" -File | Sort-Object Name | ForEach-Object {
        $fm = Get-Frontmatter $_.FullName
        if ($fm -and $fm.ContainsKey("name")) {
            $agentRows += "| ``$($fm['name'])`` | $(Format-Desc $fm['description']) |"
        }
    }
    $workersDir = Join-Path $agentsDir "_workers"
    if (Test-Path $workersDir) {
        Get-ChildItem $workersDir -Filter "*.md" -File | Sort-Object Name | ForEach-Object {
            $fm = Get-Frontmatter $_.FullName
            if ($fm -and $fm.ContainsKey("name")) {
                $agentRows += "| ``_workers/$($fm['name'])`` | $(Format-Desc $fm['description']) |"
            }
        }
    }
}

# --- Emit ---
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("# CATALOG - Vibeforge skills and agents (AUTO-GENERATED)")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("> DO NOT EDIT BY HAND. Generated by `scripts/build-catalog.ps1` from the real")
[void]$sb.AppendLine("> frontmatter of the files on disk. Factual source of truth for orchestrator")
[void]$sb.AppendLine("> agents (lead): NEVER invoke a skill/agent absent from this catalog.")
[void]$sb.AppendLine("> Re-generate after adding/removing any skill or agent.")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("## Invocable skills ($($skillRows.Count))")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("| Skill | Description |")
[void]$sb.AppendLine("|-------|-------------|")
$skillRows | ForEach-Object { [void]$sb.AppendLine($_) }
[void]$sb.AppendLine("")
[void]$sb.AppendLine("## Instantiable agents ($($agentRows.Count))")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("| Agent | Description |")
[void]$sb.AppendLine("|-------|-------------|")
$agentRows | ForEach-Object { [void]$sb.AppendLine($_) }

$dir = Split-Path $OutFile -Parent
if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
[System.IO.File]::WriteAllText($OutFile, $sb.ToString(), (New-Object System.Text.UTF8Encoding $false))

Write-Host "CATALOG generated: $OutFile"
Write-Host "  Skills: $($skillRows.Count)"
Write-Host "  Agents: $($agentRows.Count)"
