# PreCompact hook -- Vibeforge (R018)
# Anti-amnesia net: just before a compaction (manual or auto), reminds you to
# flush the persistent framing memory (MEMORY-cadrage.md) if we are in a
# project framing context. Non-blocking (exit 0). Pure ASCII.

$ErrorActionPreference = "SilentlyContinue"

$cwd = (Get-Location).Path
$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

$logDir = Join-Path $cwd ".claude\logs"
if (-not (Test-Path $logDir)) {
    New-Item -ItemType Directory -Path $logDir -Force | Out-Null
}
$logFile = Join-Path $logDir "pre-compact-hook.log"

# Read stdin payload (trigger = manual|auto)
$trigger = "unknown"
try {
    $raw = [Console]::In.ReadToEnd()
    if ($raw) {
        $payload = $raw | ConvertFrom-Json
        if ($payload.trigger) { $trigger = $payload.trigger }
    }
} catch {}

"$timestamp [PreCompact] trigger=$trigger cwd=$cwd" | Out-File -FilePath $logFile -Append -Encoding utf8

# Look for a relevant MEMORY-cadrage.md
$cadrageFiles = @()
$rootCadrage = Join-Path $cwd "MEMORY-cadrage.md"
if (Test-Path $rootCadrage) { $cadrageFiles += $rootCadrage }

$metaDir = Join-Path $cwd "projets-meta"
if (Test-Path $metaDir) {
    $found = Get-ChildItem -Path $metaDir -Recurse -Filter "MEMORY-cadrage.md" -ErrorAction SilentlyContinue | Select-Object -First 10
    foreach ($f in $found) { $cadrageFiles += $f.FullName }
}

# Heuristic: are we in a lab or a project (so framing is likely)?
$inCadrageContext = ($cadrageFiles.Count -gt 0) -or (Test-Path (Join-Path $cwd "registres")) -or (Test-Path (Join-Path $cwd "registers"))

if (-not $inCadrageContext) {
    "$timestamp [PreCompact] outside framing context, skip" | Out-File -FilePath $logFile -Append -Encoding utf8
    exit 0
}

# Write a persistent reminder (re-read at next start / consultable)
$reminderFile = Join-Path $cwd ".claude\cadrage-precompact-reminder.md"
$staleness = ""
if ($cadrageFiles.Count -gt 0) {
    $mostRecent = (Get-Item $cadrageFiles | Sort-Object LastWriteTime -Descending | Select-Object -First 1)
    $ageMin = [int]((Get-Date) - $mostRecent.LastWriteTime).TotalMinutes
    $staleness = "Last update to MEMORY-cadrage.md: $ageMin min ago ($($mostRecent.FullName))."
} else {
    $staleness = "NO MEMORY-cadrage.md found. If this is a long framing, create one (Vibeforge template)."
}

$content = @"
# Pre-compaction reminder (R018) - $timestamp

A compaction ($trigger) is about to trigger in this framing context.

$staleness

BEFORE letting the context get compacted, make sure the framing memory is up to
date, otherwise the "why", the roadmap and the decisions risk being lost:

- Run ``/save-cadrage`` to flush decisions, roadmap and key facts to disk.
- As a last resort if the memory is already lost: ``/recover-cadrage <session-id>``.

> Auto-generated by hooks/pre-compact.ps1. Delete this file once the memory is saved.
"@

Set-Content -Path $reminderFile -Value $content -Encoding utf8
"$timestamp [PreCompact] reminder written -> $reminderFile (cadrage files: $($cadrageFiles.Count))" | Out-File -FilePath $logFile -Append -Encoding utf8

# Visible message (stdout) to nudge the agent in context
Write-Output "[Vibeforge R018] Compaction imminent. Remember /save-cadrage so you do not lose the framing memory (decisions, roadmap, why). $staleness"

exit 0
