# SessionStart hook -- Vibeforge
#
# Auto-triggers /dream when it has been >24h since the last consolidation pass
# AND there has been recent activity in the current working tree. Drops a
# .claude/dream-auto-pending.md marker that the main agent reads at bootstrap.
#
# Also runs a fast R016 word-count check (agent MEMORY.md <= 500 words) over
# this standalone lab's own agent-contexts/ + projets-meta/*/agent-contexts/
# trees and drops .claude/memory-wordcount-pending.md on VIOLATION (>=500).
#
# Non-blocking by design: any failure here must never break SessionStart.
# ASCII-safe code to avoid PowerShell 5.1 encoding bugs on Windows.

$ErrorActionPreference = "SilentlyContinue"

$cwd = (Get-Location).Path
$logDir = Join-Path $cwd ".claude\logs"
if (-not (Test-Path $logDir)) {
    New-Item -ItemType Directory -Path $logDir -Force | Out-Null
}
$logFile = Join-Path $logDir "session-start-hook.log"
$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

"$timestamp [SessionStart] cwd=$cwd" | Out-File -FilePath $logFile -Append -Encoding utf8

# R016 word-count check -- standalone lab shape: agent-contexts/ IS the
# lab's own MEMORY level (no nested vibeforge/ or lab-*/ dirs to walk).
try {
    $wordWarnThreshold = 450
    $wordViolationThreshold = 500
    $labMemoryFiles = @()

    $labAgentCtx = Join-Path $cwd "agent-contexts"
    if (Test-Path $labAgentCtx) {
        Get-ChildItem -Path $labAgentCtx -Recurse -Filter "MEMORY.md" -ErrorAction SilentlyContinue | ForEach-Object {
            $labMemoryFiles += $_.FullName
        }
    }
    $projetsMetaDir = Join-Path $cwd "projets-meta"
    if (Test-Path $projetsMetaDir) {
        Get-ChildItem -Path $projetsMetaDir -Directory -ErrorAction SilentlyContinue | ForEach-Object {
            $projetCtx = Join-Path $_.FullName "agent-contexts"
            if (Test-Path $projetCtx) {
                Get-ChildItem -Path $projetCtx -Recurse -Filter "MEMORY.md" -ErrorAction SilentlyContinue | ForEach-Object {
                    $labMemoryFiles += $_.FullName
                }
            }
        }
    }

    $wcViolations = @()
    $wcWarnings = @()
    foreach ($mf in $labMemoryFiles) {
        $content = Get-Content -Path $mf -Raw -Encoding utf8 -ErrorAction SilentlyContinue
        $wordCount = 0
        if (-not [string]::IsNullOrWhiteSpace($content)) {
            $wordCount = ($content -split '\s+' | Where-Object { $_.Length -gt 0 }).Count
        }
        if ($wordCount -ge $wordViolationThreshold) {
            $wcViolations += "$mf : $wordCount words"
        } elseif ($wordCount -ge $wordWarnThreshold) {
            $wcWarnings += "$mf : $wordCount words"
        }
    }

    $wcStatus = "OK"
    if ($wcViolations.Count -gt 0) { $wcStatus = "VIOLATION" } elseif ($wcWarnings.Count -gt 0) { $wcStatus = "WARNING" }
    "$timestamp [SessionStart] R016 word-count STATUS: $wcStatus ($($wcViolations.Count) violation / $($wcWarnings.Count) warning / $($labMemoryFiles.Count) scanned)" | Out-File -FilePath $logFile -Append -Encoding utf8

    if ($wcViolations.Count -gt 0) {
        $wcPendingFile = Join-Path $cwd ".claude\memory-wordcount-pending.md"
        $wcBody = (($wcViolations | ForEach-Object { "[VIOLATION] $_" }) + ($wcWarnings | ForEach-Object { "[WARNING]   $_" })) -join "`n"
        @"
# R016: MEMORY.md over the word ceiling (>=500 words)

STATUS: $wcStatus

$wcBody

Prune the oldest / least-cited entries in each MEMORY.md above BEFORE any new
write (archive pruned entries into agent-contexts/<agent>/journal.md).

Generated by the SessionStart hook at $timestamp.
"@ | Out-File -FilePath $wcPendingFile -Encoding utf8
        "$timestamp [SessionStart] memory-wordcount-pending created (VIOLATION detected)" | Out-File -FilePath $logFile -Append -Encoding utf8
    }
} catch {
    "$timestamp [SessionStart] R016 word-count check failed: $($_.Exception.Message)" | Out-File -FilePath $logFile -Append -Encoding utf8
}

# Auto-trigger /dream if >24h since the last pass + recent activity (R009).
# The marker and the activity check are based on the current working tree (the
# lab / meta-project the user is in), so this works regardless of where the
# plugin is installed.
try {
    $lastDreamFile = Join-Path $cwd ".claude\last-dream-ts.txt"
    $autoTriggerFile = Join-Path $cwd ".claude\dream-auto-pending.md"
    $shouldTrigger = $false
    $reason = ""

    # Only consider triggering inside a git working tree (otherwise there is no
    # reliable notion of "recent activity").
    $isGitRepo = (Test-Path (Join-Path $cwd ".git")) -or `
        ((& git -C $cwd rev-parse --is-inside-work-tree 2>$null) -eq "true")

    if ($isGitRepo) {
        if (-not (Test-Path $lastDreamFile)) {
            $shouldTrigger = $true
            $reason = "never run in this working tree"
        } else {
            $lastDreamStr = (Get-Content $lastDreamFile -Raw -ErrorAction SilentlyContinue).Trim()
            try {
                $lastDream = [DateTime]::Parse($lastDreamStr)
                $hoursSinceDream = ((Get-Date) - $lastDream).TotalHours
                if ($hoursSinceDream -ge 24) {
                    $shouldTrigger = $true
                    $reason = "last pass $([math]::Round($hoursSinceDream, 1)) hours ago"
                }
            } catch {
                "$timestamp [SessionStart] last-dream-ts.txt unreadable: $($_.Exception.Message)" | Out-File -FilePath $logFile -Append -Encoding utf8
            }
        }

        # Require some recent activity (no point consolidating nothing).
        if ($shouldTrigger) {
            $oneWeekAgo = (Get-Date).AddDays(-7).ToString("yyyy-MM-dd HH:mm:ss")
            $recentCommits = (& git -C $cwd log --since="$oneWeekAgo" --oneline 2>$null | Measure-Object -Line).Lines
            if ($recentCommits -lt 1) {
                $shouldTrigger = $false
                $reason = "no recent activity ($recentCommits commits in 7d), skip"
            }
        }
    } else {
        $reason = "not a git working tree, skip"
    }

    if ($shouldTrigger) {
        $autoDir = Split-Path $autoTriggerFile -Parent
        if (-not (Test-Path $autoDir)) {
            New-Item -ItemType Directory -Path $autoDir -Force | Out-Null
        }
        $autoTriggerContent = @"
# Auto-trigger /dream pending (R009)

Status: $reason

At the start of this session, the main agent MUST invoke ``/dream`` automatically
BEFORE any other action. The skill:
1. Proposes MEMORY updates from recent journals + git history
2. Invokes dream-validator to filter apply/reject/defer
3. Applies the high-confidence ``apply`` items automatically
4. Logs the ``reject`` items
5. Preserves the ``defer`` items for later manual review

Auto mode (no user validation required). Periodic audits via
``/metrics-report --focus=memory-consolidation``.

Generated by the SessionStart hook at $timestamp.
"@
        $autoTriggerContent | Out-File -FilePath $autoTriggerFile -Encoding utf8
        "$timestamp [SessionStart] dream-auto-pending created ($reason)" | Out-File -FilePath $logFile -Append -Encoding utf8
    } else {
        "$timestamp [SessionStart] dream auto skip ($reason)" | Out-File -FilePath $logFile -Append -Encoding utf8
    }
} catch {
    "$timestamp [SessionStart] dream auto check failed: $($_.Exception.Message)" | Out-File -FilePath $logFile -Append -Encoding utf8
}

exit 0
